name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint actions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: remark-lint
        uses: reviewdog/action-remark-lint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check

  test:
    runs-on: ubuntu-latest
    name: Test branch-name
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run test
        id: branch-name
        uses: ./
      - name: Show output
        run: |
          echo "Current Branch: ${{ steps.branch-name.outputs.current_branch }}"
          echo "Base Ref: ${{ steps.branch-name.outputs.base_ref_branch }}"
          echo "Head Ref: ${{ steps.branch-name.outputs.head_ref_branch }}"
          echo "Ref: ${{ steps.branch-name.outputs.ref_branch }}"
          echo "Is Default: ${{ steps.branch-name.outputs.is_default }}"
      - name: Check is_default for pull request
        if: github.event_name == 'pull_request' && steps.branch-name.outputs.is_default != 'false'
        run: |
          echo "Is default is invalid: ${{ steps.branch-name.outputs.is_default }}"
          exit 1
      - name: Check is_default for non pull request
        if: github.event_name != 'pull_request' && steps.branch-name.outputs.is_default != 'true'
        run: |
          echo "Is default is invalid: ${{ steps.branch-name.outputs.is_default }}"
          exit 1
      - name: Test base ref output
        if: github.event_name == 'pull_request' && !steps.branch-name.outputs.base_ref_branch
        run: |
          echo "Base ref unset: ${{ steps.branch-name.outputs.base_ref_branch }}"
          exit 1
      - name: Test head ref output
        if: github.event_name == 'pull_request' && !steps.branch-name.outputs.head_ref_branch
        run: |
          echo "Head ref unset: ${{ steps.branch-name.outputs.head_ref_branch }}"
          exit 1
      - name: Test ref output
        if: "!steps.branch-name.outputs.ref_branch"
        run: |
          echo "Ref unset: ${{ steps.branch-name.outputs.ref_branch }}"
          exit 1
      - name: Test current branch output for pull_request event.
        if: github.event_name == 'pull_request' && !steps.branch-name.outputs.current_branch
        run: |
          echo "Current branch unset: ${{ steps.branch-name.outputs.current_branch }}"
          exit 1
      - name: Test current branch output for push event.
        if: github.event_name == 'push' && !steps.branch-name.outputs.current_branch
        run: |
          echo "Current branch unset: ${{ steps.branch-name.outputs.current_branch }}"
          exit 1
      
